import { RoutesDataItem } from "@/utils/routes";
import BlankLayout from "@/layouts/BlankLayout.vue";

const IndexLayoutRoutes: Array<RoutesDataItem> = [
  //门店菜单及权限
  {
    icon: "home",
    title: "商品",
    path: "/product",
    roles: ["product"],
    // redirect: "productlist",
    // component: BlankLayout,
    component: () => import("@/views/product/productlist.vue"),
    
  },
  {
    icon: "home",
    title: "新增商品",
    path: "/newproduct",
    roles: ["newproduct"],
    component: () => import("@/views/product/newproduct.vue"),
    hidden: true,
    selectLeftMenu: "/product",
  },

  {
    icon: "detail",
    title: "进货",
    path: "/purchase",
    redirect: "/purchase/noreceive",
    component: BlankLayout,
    roles: ["purchase"],
    children: [
      {
        // icon: "detail",
        title: "待收货",
        path: "/purchase/noreceive",
        roles: ["noreceive"],
        component: () => import("@/views/purchase/noreceive.vue"),
      },
      {
        // icon: "detail",
        title: "已收货",
        path: "/purchase/receive",
        roles: ["receive"],
        component: () => import("@/views/purchase/receive.vue"),
      },
      {
        // icon: "detail",
        title: "表格",
        path: "/purchase/tab",
        roles: ["tab"],
        component: () => import("@/views/purchase/tab.vue"),
      },
    ],
  },
  {
    icon: "detail",
    title: "盘点",
    path: "/inventory",
    redirect: "/inventory/nocheckproduct",
    component: BlankLayout,
    roles: ["inventory"],
    children: [
      {
        title: "待盘点",
        path: "/inventory/nocheckproduct",
        roles: ["nocheckproduct"],
        component: () => import("@/views/inventory/nocheckproduct.vue"),
      },
      {
        title: "已盘点",
        path: "/inventory/checkproduct",
        roles: ["checkproduct"],
        component: () => import("@/views/inventory/checkproduct.vue"),
      },
    ],
  },
  {
    icon: "detail",
    title: "出售",
    path: "/sale",
    redirect: "/sale/sales",
    component: BlankLayout,
    roles: ["sale"],
    children: [
      {
        // icon: "detail",
        title: "待出售 ",
        path: "/sale/nosale",
        roles: ["nosale"],
        component: () => import("@/views/sale/nosale.vue"),
      },
      {
        // icon: "detail",
        title: "已出售",
        path: "/sale/sales",
        roles: ["sales"],
        component: () => import("@/views/sale/sales.vue"),
      },
    ],
  },
  {
    icon: "detail",
    title: "设置",
    path: "/setting",
    redirect: "/setting/storelist",
    component: BlankLayout,
    roles: ["setting"],
    children: [
      {
        // icon: "detail",
        title: "门店列表",
        path: "/setting/storelist",
        roles: ["storelist"],
        component: () => import("@/views/setting/storelist.vue"),
      },
      {
        // icon: "detail",
        title: "新增门店",
        path: "/setting/newstore",
        roles: ["newstore"],
        component: () => import("@/views/setting/newstore.vue"),
        hidden: true,
        selectLeftMenu: "/setting/storelist",
      },
      {
        // icon: "detail",
        title: "员工管理",
        path: "/setting/clerklist",
        roles: ["clerklist"],
        component: () => import("@/views/setting/clerklist.vue"),
      },
      {
        // icon: "detail",
        title: "新增店员",
        path: "/setting/newclerk",
        roles: ["newclerk"],
        component: () => import("@/views/setting/newclerk.vue"),
        selectLeftMenu: "/setting/clerklist",
        hidden: true,
      },
      {
        // icon: "detail",
        title: "岗位管理",
        path: "/setting/role",
        roles: ["role"],
        component: import("@/views/setting/rolelist.vue"),
      },
      {
        // icon: "detail",
        title: "权限分配",
        path: "/setting/Authority",
        roles: ["Authority"],
        component: () => import("@/views/setting/Authority.vue"),
        hidden: true,
        selectLeftMenu: "/setting/rolelist",
      },
      {
        icon: "detail",
        title: "新增角色",
        path: "/setting/newrole",
        roles: ["newrole"],
        redirect: "/setting/newrole",
        component: import("@/views/setting/newrole.vue"),
      },
      {
        // icon: "detail",
        title: "修改密码",
        path: "/setting/editpsw",
        roles: ["editpsw"],
        component: () => import("@/views/setting/editpsw.vue"),
      },
      {
        // icon: "detail",

        title: "机具管理",
        path: "/setting/machine",
        roles: ["machine"],
        component: () => import("@/views/setting/machine.vue"),
      },
      {
        // icon: "detail",
        title: "广告管理",
        path: "/setting/advertmentlist",
        roles: ["advertmentlist"],
        component: () => import("@/views/setting/advertmentlist.vue"),
      },
      {
        icon: "detail",
        title: "新增广告",
        path: "/setting/newadvertment",
        roles: ["newadvertment"],
        component: () => import("@/views/setting/newadvertment.vue"),
        selectLeftMenu: "/setting/advertmentlist",
        hidden: true,
      },
      // {
      //   title: "企业信息",
      //   path: "/setting/CorporateInformation",
      //   roles: ["machine"],
      //   component: () => import("@/views/setting/CorporateInformation.vue"),
      // },
    ],
  },
  //凯华管理员
  {
    icon: "detail",
    title: "系统用户",
    path: "/sysuser",
    redirect: "/sysuser/customer",
    component: BlankLayout,
    roles: ["sysuser"],
    children: [
      {
        title: "消费者",
        path: "customer",
        roles: ["customer"],
        component: () => import("@/views/sysuser/customer.vue"),
      },
      {
        title: "门店",
        path: "/store",
        component: () => import("@/views/store/storelist.vue"),
        roles: ["store"],
      },
      {
       
        title: "物流配送",
        path: "/logistics",
        roles: ["logistics"],
        component: () => import("@/views/sysuser/logistics.vue"),
      },
      {
        title: "物流仓库",
        path: "/warehouse",
        roles: ["warehouse"],
        component: () => import("@/views/sysuser/warehouse.vue"),
      },
      {
        title: "工厂",
        path: "/factory",
        roles: ["factory"],
        component: () => import("@/views/sysuser/factory.vue"),
      },
      {
        title: "保险",
        path: "/insurance",
        roles: ["insurance"],
        component: () => import("@/views/sysuser/insurance.vue"),
      }, {
        title: "银行",
        path: "/bank",
        roles: ["bank"],
        component: () => import("@/views/sysuser/bank.vue"),
      },
      
    ],
  },
  {
    title: "商品详情",
    path: "/productinfo",
    component: () => import("@/views/product/productinfo.vue"),
    roles: ["productinfo"],
    hidden: true,
    selectLeftMenu: "/product",
  },
  
  {
    title: "审核",
    path: "/storeapproval",
    component: () => import("@/views/store/storeapproval.vue"),
    roles: ["storeapproval"],
    hidden: true,
    selectLeftMenu: "/store",
  }, {
    icon: "set",
    title: "凯华内部设置",
    path: "/khset",
    redirect: "/khset/rolepower",
    component: BlankLayout,
    roles: ["khset"],
    children: [
      {
        
        title: "角色权限",
        path: "/rolepower",
        roles: ["rolepower"],
        component: () => import("@/views/khset/rolepower.vue"),
      },
      {
        
        title: "功能菜单",
        path: "/funcmenu",
        roles: ["funcmenu"],
        component: () => import("@/views/khset/funcmenu.vue"),
      },
       
    ],
  },
  {
    icon: "detail",
    title: "商品信息管理",
    path: "/commodity",
    redirect: "/commodity/brandinfo",
    component: BlankLayout,
    roles: ["commodity"],
    children: [
      {
        icon: "detail",
        title: "品牌信息",
        path: "brandinfo",
        roles: ["brandinfo"],
        component: () => import("@/views/commodity/brandinfo.vue"),
      },
      {
        icon: "detail",
        title: "商品信息",
        path: "commodityinfo",
        roles: ["commodityinfo"],
        component: () => import("@/views/commodity/commodityinfo.vue"),
      },
      {
        icon: "detail",
        title: "新增商品",
        path: "newcommodity",
        roles: ["newcommodity"],
        hidden: true,
        component: () => import("@/views/commodity/newcommodity.vue"),
      },
      {
        icon: "detail",
        title: "商品库存",
        path: "commoditystock",
        roles: ["commoditystock"],
        component: () => import("@/views/commodity/commoditystock.vue"),
      },
      {
        icon: "detail",
        title: "发货管理",
        path: "commoditysend",
        roles: ["commoditysend"],
        component: () => import("@/views/commodity/commoditysend.vue"),
      },
      {
        icon: "detail",
        title: "物流管理",
        path: "commoditylogistics",
        roles: ["commoditylogistics"],
        component: () => import("@/views/commodity/commoditylogistics.vue"),
      },
    ],
  },
  {
    icon: "detail",
    title: "交易支付管理",
    path: "/pay",
    redirect: "/pay/brandinfo",
    component: BlankLayout,
    roles: ["pay"],
    children: [
      {
        icon: "detail",
        title: "开户信息",
        path: "payaccount",
        roles: ["payaccount"],
        component: () => import("@/views/pay/payaccount.vue"),
      },
      {
        icon: "detail",
        title: "交易记录",
        path: "paylog",
        roles: ["paylog"],
        component: () => import("@/views/pay/paylog.vue"),
      },
      {
        icon: "detail",
        title: "商品库存",
        path: "paysettlement",
        roles: ["paysettlement"],
        component: () => import("@/views/pay/paysettlement.vue"),
      },
    ],
  },
 
  {
    icon: "detail",
    title: "商品检索认证",
    path: "/attestation",
    redirect: "/attestation/generatecode",
    component: BlankLayout,
    roles: ["attestation"],
    children: [
      {
        icon: "detail",
        title: "赋码管理",
        path: "generatecode",
        roles: ["generatecode"],
        component: () => import("@/views/attestation/generatecode.vue"),
      },
      {
        icon: "detail",
        title: "容错处理",
        path: "faulttolerant",
        roles: ["faulttolerant"],
        component: () => import("@/views/attestation/faulttolerant.vue"),
      },
      {
        icon: "detail",
        title: "伪码认证",
        path: "codeauthentication",
        roles: ["codeauthentication"],
        component: () => import("@/views/attestation/codeauthentication.vue"),
      },
      {
        icon: "detail",
        title: "认证举报",
        path: "attestationreport",
        roles: ["attestationreport"],
        component: () => import("@/views/attestation/attestationreport.vue"),
      },
    ],
  },
  {
    icon: "detail",
    title: "商品状态跟踪",
    path: "/commoditystatu",
    redirect: "/commoditystatu/commoditydistribution",
    component: BlankLayout,
    roles: ["commoditystatu"],
    children: [
      {
        icon: "detail",
        title: "商品分布",
        path: "commoditydistribution",
        roles: ["commoditydistribution"],
        component: () =>
          import("@/views/commoditystatu/commoditydistribution.vue"),
      },
      {
        icon: "detail",
        title: "商品追溯",
        path: "commoditysource",
        roles: ["commoditysource"],
        component: () => import("@/views/commoditystatu/commoditysource.vue"),
      },
      {
        icon: "detail",
        title: "销售异常",
        path: "saleabnormal",
        roles: ["saleabnormal"],
        component: () => import("@/views/commoditystatu/saleabnormal.vue"),
      },
      {
        icon: "detail",
        title: "消费用户",
        path: "consumer",
        roles: ["consumer"],
        component: () => import("@/views/commoditystatu/consumer.vue"),
      },
    ],
  },
  {
    icon: "detail",
    title: "商品促销服务",
    path: "/promotion",
    redirect: "/promotion/commoditydistribution",
    component: BlankLayout,
    roles: ["promotion"],
    children: [
      {
        icon: "detail",
        title: "广告推送",
        path: "advertisingpush",
        roles: ["advertisingpush"],
        component: () => import("@/views/promotion/advertisingpush.vue"),
      },
      {
        icon: "detail",
        title: "企业红包",
        path: "enterpriseredpacket",
        roles: ["enterpriseredpacket"],
        component: () => import("@/views/promotion/enterpriseredpacket.vue"),
      },
    ],
  },
  {
    icon: "detail",
    title: "商城信息管理",
    path: "/mall",
    redirect: "/mall/mallcommodity",
    component: BlankLayout,
    roles: ["mall"],
    children: [
      {
        icon: "detail",
        title: "商品管理",
        path: "mallcommodity",
        roles: ["mallcommodity"],
        component: () => import("@/views/mall/mallcommodity.vue"),
      },
      {
        icon: "detail",
        title: "物流管理",
        path: "malllogistics",
        roles: ["malllogistics"],
        component: () => import("@/views/mall/malllogistics.vue"),
      },
      {
        icon: "detail",
        title: "活动管理",
        path: "mallactivity",
        roles: ["mallactivity"],
        component: () => import("@/views/mall/mallactivity.vue"),
      },
      {
        icon: "detail",
        title: "订单管理",
        path: "mallorder",
        roles: ["mallorder"],
        component: () => import("@/views/mall/mallorder.vue"),
      },
      {
        icon: "detail",
        title: "发票管理",
        path: "mallticket",
        roles: ["mallticket"],
        component: () => import("@/views/mall/mallticket.vue"),
      },
      {
        icon: "detail",
        title: "退货管理",
        path: "returncommodity",
        roles: ["returncommodity"],
        component: () => import("@/views/mall/returncommodity.vue"),
      },
      {
        icon: "detail",
        title: "广告管理",
        path: "malladvert",
        roles: ["malladvert"],
        component: () => import("@/views/mall/malladvert.vue"),
      },
    ],
  },
];

export default IndexLayoutRoutes;
