import { RoutesDataItem } from "@/utils/routes";
import BlankLayout from "@/layouts/BlankLayout.vue";

const IndexLayoutRoutes: Array<RoutesDataItem> = [
  //门店菜单及权限
  {
    icon: "home",
    title: "商品",
    path: "/product",
    roles: ["product"],
    // redirect: "productlist",
    // component: BlankLayout,
    component: () => import("@/views/product/productlist.vue"),
    
  },
  {
    icon: "home",
    title: "新增商品",
    path: "/newproducttwo",
    roles: ["newproducttwo"],
    component: () => import("@/views/product/newproducttwo.vue"),
    hidden: true,
    selectLeftMenu: "/product",
  },
  {
    icon: "home",
    title: "新增商品",
    path: "/newproduct",
    roles: ["newproduct"],
    component: () => import("@/views/product/newproduct.vue"),
    hidden: true,
    selectLeftMenu: "/product",
  },
 
  
  
  {
    icon: "detail",
    title: "设置",
    path: "/setting",
    redirect: "/setting/storelist",
    component: BlankLayout,
    roles: ["setting"],
    children: [
      {
        // icon: "detail",
        title: "门店列表",
        path: "/setting/storelist",
        roles: ["storelist"],
        component: () => import("@/views/setting/storelist.vue"),
      },
      {
        // icon: "detail",
        title: "新增门店",
        path: "/setting/newstoretwo",
        roles: ["newstoretwo"],
        component: () => import("@/views/setting/newstoretwo.vue"),
        hidden: true,
        selectLeftMenu: "/setting/storelist",
      },
      {
        // icon: "detail",
        title: "新增门店",
        path: "/setting/newstore",
        roles: ["newstore"],
        component: () => import("@/views/setting/newstore.vue"),
        hidden: true,
        selectLeftMenu: "/setting/storelist",
      },
      {
        // icon: "detail",
        title: "员工管理",
        path: "/setting/clerklist",
        roles: ["clerklist"],
        component: () => import("@/views/setting/clerklist.vue"),
      },
      {
        // icon: "detail",
        title: "新增店员",
        path: "/setting/newclerktwo",
        roles: ["newclerktwo"],
        component: () => import("@/views/setting/newclerktwo.vue"),
        selectLeftMenu: "/setting/clerklist",
        hidden: true,
      },
      {
        // icon: "detail",
        title: "新增店员",
        path: "/setting/newclerk",
        roles: ["newclerk"],
        component: () => import("@/views/setting/newclerk.vue"),
        selectLeftMenu: "/setting/clerklist",
        hidden: true,
      },
      {
        // icon: "detail",
        title: "岗位管理",
        path: "/setting/role",
        roles: ["role"],
        component: import("@/views/setting/rolelist.vue"),
      },
      {
        // icon: "detail",
        title: "权限分配",
        path: "/setting/Authority",
        roles: ["Authority"],
        component: () => import("@/views/setting/Authority.vue"),
        hidden: true,
        selectLeftMenu: "/setting/rolelist",
      },
      {
        icon: "detail",
        title: "新增角色",
        path: "/setting/newrole",
        roles: ["newrole"],
        redirect: "/setting/newrole",
        component: import("@/views/setting/newrole.vue"),
      },
      {
        // icon: "detail",
        title: "修改密码",
        path: "/setting/editpsw",
        roles: ["editpsw"],
        component: () => import("@/views/setting/editpsw.vue"),
      },
      {
        // icon: "detail",

        title: "机具管理",
        path: "/setting/machine",
        roles: ["machine"],
        component: () => import("@/views/setting/machine.vue"),
      },
      {
        icon: "detail",
        title: "新增机具",
        path: "/setting/machinenew",
        roles: ["machinenew"],
        component: () => import("@/views/setting/machinenew.vue"),
        selectLeftMenu: "/setting/machine",
        hidden: true,
      },
      {
        // icon: "detail",
        title: "广告管理",
        path: "/setting/advertmentlist",
        roles: ["advertmentlist"],
        component: () => import("@/views/setting/advertmentlist.vue"),
      },
      {
        icon: "detail",
        title: "新增广告",
        path: "/setting/newadvertmenttwo",
        roles: ["newadvertmenttwo"],
        component: () => import("@/views/setting/newadvertmenttwo.vue"),
        selectLeftMenu: "/setting/advertmentlist",
        hidden: true,
      },
      {
        icon: "detail",
        title: "新增广告",
        path: "/setting/newadvertment",
        roles: ["newadvertment"],
        component: () => import("@/views/setting/newadvertment.vue"),
        selectLeftMenu: "/setting/advertmentlist",
        hidden: true,
      },
      // {
      //   title: "企业信息",
      //   path: "/setting/CorporateInformation",
      //   roles: ["machine"],
      //   component: () => import("@/views/setting/CorporateInformation.vue"),
      // },
    ],
  },
  //凯华管理员
  {
    icon: "detail",
    title: "系统用户",
    path: "/sysuser",
    redirect: "/sysuser/customer",
    component: BlankLayout,
    roles: ["sysuser"],
    children: [
      {
        title: "消费者",
        path: "customer",
        roles: ["customer"],
        component: () => import("@/views/sysuser/customer.vue"),
      },
      {
        title: "门店",
        path: "/store",
        component: () => import("@/views/store/storelist.vue"),
        roles: ["store"],
      },
      {
       
        title: "物流配送",
        path: "/logistics",
        roles: ["logistics"],
        component: () => import("@/views/sysuser/logistics.vue"),
      },
      {
        title: "物流仓库",
        path: "/warehouse",
        roles: ["warehouse"],
        component: () => import("@/views/sysuser/warehouse.vue"),
      },
      {
        title: "工厂",
        path: "/factory",
        roles: ["factory"],
        component: () => import("@/views/sysuser/factory.vue"),
      },
      {
        title: "保险",
        path: "/insurance",
        roles: ["insurance"],
        component: () => import("@/views/sysuser/insurance.vue"),
      }, {
        title: "银行",
        path: "/bank",
        roles: ["bank"],
        component: () => import("@/views/sysuser/bank.vue"),
      },
      
    ],
  },
  {
    title: "商品详情",
    path: "/productinfo",
    component: () => import("@/views/product/productinfo.vue"),
    roles: ["productinfo"],
    hidden: true,
    selectLeftMenu: "/product",
  },
  {
    title: "审核",
    path: "/storeapproval",
    component: () => import("@/views/store/storeapproval.vue"),
    roles: ["storeapproval"],
    hidden: true,
    selectLeftMenu: "/store",
  }, {
    icon: "set",
    title: "凯华内部设置",
    path: "/khset",
    redirect: "/khset/rolepower",
    component: BlankLayout,
    roles: ["khset"],
    children: [
      {
        
        title: "角色权限",
        path: "/rolepower",
        roles: ["rolepower"],
        component: () => import("@/views/khset/rolepower.vue"),
      },
      {
        
        title: "功能菜单",
        path: "/funcmenu",
        roles: ["funcmenu"],
        component: () => import("@/views/khset/funcmenu.vue"),
      },
       
    ],
  },
  {
    title: "用户级别",
    path: "/userlv",
    redirect: "/userlv/clerk/noreceive",
    component: BlankLayout,
    roles: ["userlv"],
    children: [
      {
        // icon: "detail",
        title: "门店店员 ",
        path: "/clerk",
        roles: ["clerk"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/clerk/noreceive",
            roles: ["clerknoreceive"],
            component: () => import("@/views/userlv/clerk/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/clerk/receive",
            roles: ["clerkreceive"],
            component: () => import("@/views/userlv/clerk/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/clerk/nocheckproduct",
            roles: ["clerknocheckproduct"],
            component: () => import("@/views/userlv/clerk/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/clerk/checkproduct",
            roles: ["clerkcheckproduct"],
            component: () => import("@/views/userlv/clerk/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/clerk/nosale",
            roles: ["clerknosale"],
            component: () => import("@/views/userlv/clerk/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/clerk/sales",
            roles: ["clerksales"],
            component: () => import("@/views/userlv/clerk/sales.vue"),
          },
        ],
      },
      {
        // icon: "detail",
        title: "门店店长",
        path: "/userlv/shopowner/noreceive",
        roles: ["shopowner"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/shopowner/noreceive",
            roles: ["shopownernoreceive"],
            component: () => import("@/views/userlv/shopowner/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/shopowner/receive",
            roles: ["shopownerreceive"],
            component: () => import("@/views/userlv/shopowner/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/shopowner/nocheckproduct",
            roles: ["shopownernocheckproduct"],
            component: () => import("@/views/userlv/shopowner/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/shopowner/checkproduct",
            roles: ["shopownercheckproduct"],
            component: () => import("@/views/userlv/shopowner/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/shopowner/nosale",
            roles: ["shopownernosale"],
            component: () => import("@/views/userlv/shopowner/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/shopowner/sales",
            roles: ["shopownersales"],
            component: () => import("@/views/userlv/shopowner/sales.vue"),
          },
        ],
      },
      {
        // icon: "detail",
        title: "市级经销商",
        path: "/citydistributor",
        roles: ["citydistributor"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/citydistributor/noreceive",
            roles: ["citydistributornoreceive"],
            component: () => import("@/views/userlv/citydistributor/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/citydistributor/receive",
            roles: ["citydistributorreceive"],
            component: () => import("@/views/userlv/citydistributor/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/citydistributor/nocheckproduct",
            roles: ["citydistributornocheckproduct"],
            component: () => import("@/views/userlv/citydistributor/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/citydistributor/checkproduct",
            roles: ["citydistributorcheckproduct"],
            component: () => import("@/views/userlv/citydistributor/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/citydistributor/nosale",
            roles: ["citydistributornosale"],
            component: () => import("@/views/userlv/citydistributor/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/citydistributor/sales",
            roles: ["citydistributorsales"],
            component: () => import("@/views/userlv/citydistributor/sales.vue"),
          },
        ],
      },
      {
        // icon: "detail",
        title: "省级经销商 ",
        path: "/provincedistributor",
        roles: ["provincedistributor"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/provincedistributor/noreceive",
            roles: ["provincedistributornoreceive"],
            component: () => import("@/views/userlv/provincedistributor/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/provincedistributor/receive",
            roles: ["provincedistributorreceive"],
            component: () => import("@/views/userlv/provincedistributor/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/provincedistributor/nocheckproduct",
            roles: ["provincedistributornocheckproduct"],
            component: () => import("@/views/userlv/provincedistributor/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/provincedistributor/checkproduct",
            roles: ["provincedistributorcheckproduct"],
            component: () => import("@/views/userlv/provincedistributor/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/provincedistributor/nosale",
            roles: ["provincedistributornosale"],
            component: () => import("@/views/userlv/provincedistributor/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/provincedistributor/sales",
            roles: ["provincedistributorsales"],
            component: () => import("@/views/userlv/provincedistributor/sales.vue"),
          },
        ],
      },
      {
        // icon: "detail",
        title: "全国经销商 ",
        path: "/countrydistributor",
        roles: ["countrydistributor"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/countrydistributor/noreceive",
            roles: ["countrydistributornoreceive"],
            component: () => import("@/views/userlv/countrydistributor/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/countrydistributor/receive",
            roles: ["countrydistributorreceive"],
            component: () => import("@/views/userlv/countrydistributor/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/countrydistributor/nocheckproduct",
            roles: ["countrydistributornocheckproduct"],
            component: () => import("@/views/userlv/countrydistributor/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/countrydistributor/checkproduct",
            roles: ["countrydistributorcheckproduct"],
            component: () => import("@/views/userlv/countrydistributor/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/countrydistributor/nosale",
            roles: ["countrydistributornosale"],
            component: () => import("@/views/userlv/countrydistributor/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/countrydistributor/sales",
            roles: ["countrydistributorsales"],
            component: () => import("@/views/userlv/countrydistributor/sales.vue"),
          },
        ],
      },
    ],
  },
];

export default IndexLayoutRoutes;
