import { RoutesDataItem } from "@/utils/routes";
import BlankLayout from "@/layouts/BlankLayout.vue";

const IndexLayoutRoutes: Array<RoutesDataItem> = [
  //门店菜单及权限
  {
    icon: "home",
    title: "商品",
    path: "/product",
    roles: ["product"],
    // redirect: "productlist",
    // component: BlankLayout,
    component: () => import("@/views/product/productlist.vue"),
    
  },
  {
    icon: "home",
    title: "新增商品",
    path: "/newproduct",
    roles: ["newproduct"],
    component: () => import("@/views/product/newproduct.vue"),
    hidden: true,
    selectLeftMenu: "/product",
  },
  {
    icon: "detail",
    title: "设置",
    path: "/setting",
    redirect: "/setting/storelist",
    component: BlankLayout,
    roles: ["setting"],
    children: [
      {
        // icon: "detail",
        title: "门店列表",
        path: "/setting/storelist",
        roles: ["storelist"],
        component: () => import("@/views/setting/storelist.vue"),
      },
      {
        // icon: "detail",
        title: "新增门店",
        path: "/setting/newstore",
        roles: ["newstore"],
        component: () => import("@/views/setting/newstore.vue"),
        hidden: true,
        selectLeftMenu: "/setting/storelist",
      },
      {
        // icon: "detail",
        title: "新增门店",
        path: "/setting/newstore",
        roles: ["newstore"],
        component: () => import("@/views/setting/newstore.vue"),
        hidden: true,
        selectLeftMenu: "/setting/storelist",
      },
      {
        // icon: "detail",
        title: "员工管理",
        path: "/setting/clerklist",
        roles: ["clerklist"],
        component: () => import("@/views/setting/clerklist.vue"),
      },
      {
        // icon: "detail",
        title: "新增店员",
        path: "/setting/newclerktwo",
        roles: ["newclerktwo"],
        component: () => import("@/views/setting/newclerktwo.vue"),
        selectLeftMenu: "/setting/clerklist",
        hidden: true,
      },
      {
        // icon: "detail",
        title: "新增店员",
        path: "/setting/newclerk",
        roles: ["newclerk"],
        component: () => import("@/views/setting/newclerk.vue"),
        selectLeftMenu: "/setting/clerklist",
        hidden: true,
      },
      {
        // icon: "detail",
        title: "岗位管理",
        path: "/setting/role",
        roles: ["role"],
        component: import("@/views/setting/rolelist.vue"),
      },
      {
        // icon: "detail",
        title: "权限分配",
        path: "/setting/Authority",
        roles: ["Authority"],
        component: () => import("@/views/setting/Authority.vue"),
        hidden: true,
        selectLeftMenu: "/setting/rolelist",
      },
      {
        icon: "detail",
        title: "新增角色",
        path: "/setting/newrole",
        roles: ["newrole"],
        redirect: "/setting/newrole",
        component: import("@/views/setting/newrole.vue"),
      },
      {
        // icon: "detail",
        title: "修改密码",
        path: "/setting/editpsw",
        roles: ["editpsw"],
        component: () => import("@/views/setting/editpsw.vue"),
      },
      {
        // icon: "detail",

        title: "机具管理",
        path: "/setting/machine",
        roles: ["machine"],
        component: () => import("@/views/setting/machine.vue"),
      },
      {
        icon: "detail",
        title: "新增机具",
        path: "/setting/machinenew",
        roles: ["machinenew"],
        component: () => import("@/views/setting/machinenew.vue"),
        selectLeftMenu: "/setting/machine",
        hidden: true,
      },
      {
        // icon: "detail",
        title: "广告管理",
        path: "/setting/advertmentlist",
        roles: ["advertmentlist"],
        component: () => import("@/views/setting/advertmentlist.vue"),
      },
      {
        title: "对公账户",
        path: "/setting/public",
        roles: ["public"],
        component: () => import("@/views/setting/public.vue"),
      },
      {
        title: "文件管理",
        path: "/setting/file",
        roles: ["file"],
        component: () => import("@/views/setting/file.vue"),
      },
      {
        icon: "detail",
        title: "新增广告",
        path: "/setting/newadvertmenttwo",
        roles: ["newadvertmenttwo"],
        component: () => import("@/views/setting/newadvertmenttwo.vue"),
        selectLeftMenu: "/setting/advertmentlist",
        hidden: true,
      },
      {
        icon: "detail",
        title: "新增广告",
        path: "/setting/newadvertment",
        roles: ["newadvertment"],
        component: () => import("@/views/setting/newadvertment.vue"),
        selectLeftMenu: "/setting/advertmentlist",
        hidden: true,
      },
      // {
      //   title: "企业信息",
      //   path: "/setting/CorporateInformation",
      //   roles: ["machine"],
      //   component: () => import("@/views/setting/CorporateInformation.vue"),
      // },
    ],
  },
  //凯华管理员
  {
    icon: "detail",
    title: "系统用户",
    path: "/sysuser",
    redirect: "/sysuser/customer",
    component: BlankLayout,
    roles: ["sysuser"],
    children: [
      {
        title: "消费者",
        path: "customer",
        roles: ["customer"],
        component: () => import("@/views/sysuser/customer.vue"),
      },
      {
        title: "门店",
        path: "store",
        component: () => import("@/views/store/storelist.vue"),
        roles: ["store"],
      },
      {
        title: "物流配送",
        path: "logistics",
        roles: ["logistics"],
        component: () => import("@/views/sysuser/logistics.vue"),
      },
      {
        title: "物流仓库",
        path: "warehouse",
        roles: ["warehouse"],
        component: () => import("@/views/sysuser/warehouse.vue"),
      },
      {
        title: "工厂",
        path: "factory",
        roles: ["factory"],
        component: () => import("@/views/sysuser/factory.vue"),
      },
      {
        title: "保险",
        path: "insurance",
        roles: ["insurance"],
        component: () => import("@/views/sysuser/insurance.vue"),
      }, {
        title: "银行",
        path: "bank",
        roles: ["bank"],
        component: () => import("@/views/sysuser/bank.vue"),
      },
      
    ],
  },
  {
    title: "商品详情",
    path: "/productinfo",
    component: () => import("@/views/product/productinfo.vue"),
    roles: ["productinfo"],
    hidden: true,
    selectLeftMenu: "/product",
  },
  {
    title: "审核",
    path: "/storeapproval",
    component: () => import("@/views/store/storeapproval.vue"),
    roles: ["storeapproval"],
    hidden: true,
    selectLeftMenu: "/store",
  }, {
    icon: "set",
    title: "凯华内部设置",
    path: "/khset",
    redirect: "/khset/rolepower",
    component: BlankLayout,
    roles: ["khset"],
    children: [
      {
        
        title: "角色权限",
        path: "/rolepower",
        roles: ["rolepower"],
        component: () => import("@/views/khset/rolepower.vue"),
      },
      {
        
        title: "功能菜单",
        path: "/funcmenu",
        roles: ["funcmenu"],
        component: () => import("@/views/khset/funcmenu.vue"),
      },
       
    ],
  },
  {
    title: "用户级别",
    path: "/userlv",
    redirect: "/userlv/clerk/receive/noreceive",
    component: BlankLayout,
    roles: ["userlv"],
    children: [
      {
        // icon: "detail",
        title: "门店店员 ",
        path: "/clerk",
        roles: ["clerk"],
        component: BlankLayout,
        children: [
          
          // {
          //   title: "待盘点",
          //   path: "/clerk/nocheckproduct",
          //   roles: ["clerknocheckproduct"],
          //   component: () => import("@/views/userlv/clerk/nocheckproduct.vue"),
          // },
          // {
          //   title: "已盘点",
          //   path: "/clerk/checkproduct",
          //   roles: ["clerkcheckproduct"],
          //   component: () => import("@/views/userlv/clerk/checkproduct.vue"),
          // },
          // {
          //   // icon: "detail",
          //   title: "待出售 ",
          //   path: "/clerk/nosale",
          //   roles: ["clerknosale"],
          //   component: () => import("@/views/userlv/clerk/nosale.vue"),
          // },
          // {
          //   // icon: "detail",
          //   title: "已出售",
          //   path: "/clerk/sales",
          //   roles: ["clerksales"],
          //   component: () => import("@/views/userlv/clerk/sales.vue"),
          // },
          // {
          //   // icon: "detail",
          //   title: "待开户",
          //   path: "/clerk/nobank",
          //   roles: ["clerkbank"],
          //   component: () => import("@/views/userlv/clerk/nobank.vue"),
          // },
          // {
          //   // icon: "detail",
          //   title: "已开户",
          //   path: "/clerk/bank",
          //   roles: ["clerkbank"],
          //   component: () => import("@/views/userlv/clerk/bank.vue"),
          // },
          // {
          //   // icon: "detail",
          //   title: "待推送",
          //   path: "/clerk/noguarantee",
          //   roles: ["clerkguarantee"],
          //   component: () => import("@/views/userlv/clerk/noguarantee.vue"),
          // },
          // {
          //   // icon: "detail",
          //   title: "已推送",
          //   path: "/clerk/guarantee",
          //   roles: ["clerkguarantee"],
          //   component: () => import("@/views/userlv/clerk/guarantee.vue"),
          // },
          // {
          //   title: "待盘点",
          //   path: "/clerk/nocheckproduct",
          //   roles: ["clerknocheckproduct"],
          //   component: () => import("@/views/userlv/clerk/nocheckproduct.vue"),
          // },
          // {
          //   title: "已盘点",
          //   path: "/clerk/checkproduct",
          //   roles: ["clerkcheckproduct"],
          //   component: () => import("@/views/userlv/clerk/checkproduct.vue"),
          // },
          {
            // icon: "detail",
            title: "盘货",
            path: "/clerk/check",
            roles: ["clerkcheck"],
            component: BlankLayout,
            children:[
              {
                title: "待盘货",
                path: "/clerk/check/nocheckproduct",
                roles: ["clerknocheckproduct"],
                component: () => import("@/views/userlv/clerk/check/nocheckproduct.vue"),
              },
              {
                title: "待盘货统计",
                path: "/clerk/check/nocheckproductStatistics",
                roles: ["clerknocheckproduct"],
                component: () => import("@/views/userlv/clerk/check/nocheckproductStatistics.vue"),
              },
              {
                // icon: "detail",
                title: "已盘货",
                path: "/clerk/check/checkproduct",
                roles: ["clerkcheckproduct"],
                component: () => import("@/views/userlv/clerk/check/checkproduct.vue"),
              },
              {
                title: "已盘货统计",
                path: "/clerk/check/checkproductStatistics",
                roles: ["clerkcheckproduct"],
                component: () => import("@/views/userlv/clerk/check/checkproductStatistics.vue"),
              },
            ]
          },
          {
            // icon: "detail",
            title: "收货",
            path: "/clerk/receive",
            roles: ["clerkreceive"],
            component: BlankLayout,
            children:[
              {
                title: "待收货",
                path: "/clerk/receive/noreceive",
                roles: ["clerknoreceive"],
                component: () => import("@/views/userlv/clerk/receive/noreceive.vue"),
              },
              {
                title: "待收货统计",
                path: "/clerk/receive/noreceiveStatistics",
                roles: ["clerkreceive"],
                component: () => import("@/views/userlv/clerk/receive/noreceiveStatistics.vue"),
              },
              {
                // icon: "detail",
                title: "已收货",
                path: "/clerk/receive/receive",
                roles: ["clerkreceive"],
                component: () => import("@/views/userlv/clerk/receive/receive.vue"),
              },
              {
                title: "已收货统计",
                path: "/clerk/receive/receiveStatistics",
                roles: ["clerkreceive"],
                component: () => import("@/views/userlv/clerk/receive/receiveStatistics.vue"),
              },
            ]
          },
          {
            // icon: "detail",
            title: "销售",
            path: "/clerk/sale",
            roles: ["clerksale"],
            component: BlankLayout,
            children:[
              {
                title: "待售出",
                path: "/clerk/sale/nosale",
                roles: ["clerknosale"],
                component: () => import("@/views/userlv/clerk/sale/nosale.vue"),
              },
              {
                title: "待售出统计",
                path: "/clerk/sale/nosaleStatistics",
                roles: ["clerknosale"],
                component: () => import("@/views/userlv/clerk/sale/nosaleStatistics.vue"),
              },
              {
                // icon: "detail",
                title: "已售出",
                path: "/clerk/sale/sales",
                roles: ["clerksale"],
                component: () => import("@/views/userlv/clerk/sale/sales.vue"),
              },
              {
                title: "已售出统计",
                path: "/clerk/sale/saleStatistics",
                roles: ["clerksale"],
                component: () => import("@/views/userlv/clerk/sale/saleStatistics.vue"),
              },
            ]
          },
          {
            // icon: "detail",
            title: "银行开户",
            path: "/clerk/bank",
            roles: ["clerkbank"],
            component: BlankLayout,
            children:[
              {
                title: "待开户",
                path: "/clerk/bank/nobank",
                roles: ["clerkbank"],
                component: () => import("@/views/userlv/clerk/bank/nobank.vue"),
              },
              {
                title: "待开户统计",
                path: "/clerk/bank/nobankStatistics",
                roles: ["clerkbankStatistics"],
                component: () => import("@/views/userlv/clerk/bank/nobankStatistics.vue"),
              },
              {
                // icon: "detail",
                title: "已开户",
                path: "/clerk/bank/bank",
                roles: ["clerkbank"],
                component: () => import("@/views/userlv/clerk/bank/bank.vue"),
              },
            ]
          },
          {
            // icon: "detail",
            title: "银行开户",
            path: "/clerk/insurance",
            roles: ["clerkguarantee"],
            component: BlankLayout,
            children:[
              {
                title: "待开户",
                path: "/clerk/insurance/noguarantee",
                roles: ["clerkguarantee"],
                component: () => import("@/views/userlv/clerk/insurance/noguarantee.vue"),
              },
              {
                // icon: "detail",
                title: "已开户",
                path: "/clerk/insurance/guarantee",
                roles: ["clerkguarantee"],
                component: () => import("@/views/userlv/clerk/insurance/guarantee.vue"),
              },
            ]
          },
        ],
      },
      {
        // icon: "detail",
        title: "门店店长",
        path: "/userlv/shopowner/noreceive",
        roles: ["shopowner"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/shopowner/noreceive",
            roles: ["shopownernoreceive"],
            component: () => import("@/views/userlv/shopowner/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/shopowner/receive",
            roles: ["shopownerreceive"],
            component: () => import("@/views/userlv/shopowner/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/shopowner/nocheckproduct",
            roles: ["shopownernocheckproduct"],
            component: () => import("@/views/userlv/shopowner/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/shopowner/checkproduct",
            roles: ["shopownercheckproduct"],
            component: () => import("@/views/userlv/shopowner/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/shopowner/nosale",
            roles: ["shopownernosale"],
            component: () => import("@/views/userlv/shopowner/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/shopowner/sales",
            roles: ["shopownersales"],
            component: () => import("@/views/userlv/shopowner/sales.vue"),
          },
          {
            // icon: "detail",
            title: "银行开户",
            path: "/shopowner/bank",
            roles: ["shopownerbank"],
            component: () => import("@/views/userlv/shopowner/bank.vue"),
          },
          {
            // icon: "detail",
            title: "保单推送",
            path: "/shopowner/guarantee",
            roles: ["shopownerguarantee"],
            component: () => import("@/views/userlv/shopowner/guarantee.vue"),
          },
        ],
      },
      {
        // icon: "detail",
        title: "市级经销商",
        path: "/citydistributor",
        roles: ["citydistributor"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/citydistributor/noreceive",
            roles: ["citydistributornoreceive"],
            component: () => import("@/views/userlv/citydistributor/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/citydistributor/receive",
            roles: ["citydistributorreceive"],
            component: () => import("@/views/userlv/citydistributor/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/citydistributor/nocheckproduct",
            roles: ["citydistributornocheckproduct"],
            component: () => import("@/views/userlv/citydistributor/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/citydistributor/checkproduct",
            roles: ["citydistributorcheckproduct"],
            component: () => import("@/views/userlv/citydistributor/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/citydistributor/nosale",
            roles: ["citydistributornosale"],
            component: () => import("@/views/userlv/citydistributor/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/citydistributor/sales",
            roles: ["citydistributorsales"],
            component: () => import("@/views/userlv/citydistributor/sales.vue"),
          },
          {
            // icon: "detail",
            title: "银行开户",
            path: "/citydistributor/bank",
            roles: ["citydistributorbank"],
            component: () => import("@/views/userlv/citydistributor/bank.vue"),
          },
          {
            // icon: "detail",
            title: "保单推送",
            path: "/citydistributor/guarantee",
            roles: ["citydistributorguarantee"],
            component: () => import("@/views/userlv/citydistributor/guarantee.vue"),
          },
        ],
      },
      {
        // icon: "detail",
        title: "省级经销商 ",
        path: "/provincedistributor",
        roles: ["provincedistributor"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/provincedistributor/noreceive",
            roles: ["provincedistributornoreceive"],
            component: () => import("@/views/userlv/provincedistributor/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/provincedistributor/receive",
            roles: ["provincedistributorreceive"],
            component: () => import("@/views/userlv/provincedistributor/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/provincedistributor/nocheckproduct",
            roles: ["provincedistributornocheckproduct"],
            component: () => import("@/views/userlv/provincedistributor/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/provincedistributor/checkproduct",
            roles: ["provincedistributorcheckproduct"],
            component: () => import("@/views/userlv/provincedistributor/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/provincedistributor/nosale",
            roles: ["provincedistributornosale"],
            component: () => import("@/views/userlv/provincedistributor/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/provincedistributor/sales",
            roles: ["provincedistributorsales"],
            component: () => import("@/views/userlv/provincedistributor/sales.vue"),
          },
        ],
      },
      {
        // icon: "detail",
        title: "全国经销商 ",
        path: "/countrydistributor",
        roles: ["countrydistributor"],
        component: BlankLayout,
        children: [
          {
            title: "待收货",
            path: "/countrydistributor/noreceive",
            roles: ["countrydistributornoreceive"],
            component: () => import("@/views/userlv/countrydistributor/noreceive.vue"),
          },
          {
            // icon: "detail",
            title: "已收货",
            path: "/countrydistributor/receive",
            roles: ["countrydistributorreceive"],
            component: () => import("@/views/userlv/countrydistributor/receive.vue"),
          },
          {
            title: "待盘点",
            path: "/countrydistributor/nocheckproduct",
            roles: ["countrydistributornocheckproduct"],
            component: () => import("@/views/userlv/countrydistributor/nocheckproduct.vue"),
          },
          {
            title: "已盘点",
            path: "/countrydistributor/checkproduct",
            roles: ["countrydistributorcheckproduct"],
            component: () => import("@/views/userlv/countrydistributor/checkproduct.vue"),
          },
          {
            // icon: "detail",
            title: "待出售 ",
            path: "/countrydistributor/nosale",
            roles: ["countrydistributornosale"],
            component: () => import("@/views/userlv/countrydistributor/nosale.vue"),
          },
          {
            // icon: "detail",
            title: "已出售",
            path: "/countrydistributor/sales",
            roles: ["countrydistributorsales"],
            component: () => import("@/views/userlv/countrydistributor/sales.vue"),
          },
        ],
      },
    ],
  },
];

export default IndexLayoutRoutes;
